# Generated by Django 5.2.5 on 2025-08-28 16:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='docx_file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.report_upload_path),
        ),
    ]
