# Generated by Django 5.2.5 on 2025-08-28 10:42

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Antenna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antenna_type', models.CharField(max_length=200)),
                ('mount_height_m', models.FloatField()),
                ('length_m', models.FloatField(blank=True, null=True)),
                ('width_m', models.FloatField(blank=True, null=True)),
                ('depth_m', models.FloatField(blank=True, null=True)),
                ('epa', models.FloatField(blank=True, null=True)),
                ('fpa', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antennas', to='api.tower')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docx_file', models.FileField(upload_to=api.models.report_upload_path)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='Structural Report', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.tower')),
            ],
        ),
        migrations.CreateModel(
            name='StressResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=200)),
                ('axial_stress', models.FloatField()),
                ('bending_stress', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stress_results', to='api.tower')),
            ],
        ),
    ]
