# Generated by Django 5.2.5 on 2025-08-29 21:10

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_report_docx_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='docx_file',
            field=models.FileField(default='exit', upload_to=api.models.report_upload_path),
            preserve_default=False,
        ),
    ]
