# Generated by Django 5.2.5 on 2025-08-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_report_docx_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stressresult',
            name='axial_stress',
        ),
        migrations.RemoveField(
            model_name='stressresult',
            name='bending_stress',
        ),
        migrations.AddField(
            model_name='stressresult',
            name='deflection_value_sls',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stressresult',
            name='deflection_value_uls',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stressresult',
            name='max_stress_ratio_bracings',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stressresult',
            name='max_stress_ratio_legs',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
